import Head from 'next/head';
import Link from 'next/link';
import Navbar from "./Navbar"

const Layout = ({ children, title = 'Dust Ecosystem', showSubmitProjectBtn = true }) => {
    return (
        <div className="debackground h-screen overflow-auto">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta property="og:image" content="https://i.imgur.com/LVsJYp8.jpeg" />
                <meta property="og:type" content="website" />
                <meta property="og:description" content="$DUST, a useless token that everyone on Solana uses" />
                <meta property="og:url" content="https://www.dustecosystem.xyz/" />
                <meta property="og:site_name" content="DustEcosystem" />
                <meta property="og:title" content="DustEcosystem" />
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:site" content="@DeGodsNFT" />
                <meta name="twitter:title" content="DustEcosystem" />
                <meta name="twitter:description" content="$DUST, a useless token that everyone on Solana uses" />
                <meta name="twitter:image" content="https://i.imgur.com/LVsJYp8.jpeg" />
            </Head>
            <div className="w-full max-w-[1600px] mx-auto">
                <Navbar showSubmitProjectBtn={showSubmitProjectBtn}/>
                {children}
            </div>
        </div>
    )
}

export default Layout