import Head from 'next/head'
import Navbar from '../components/Navbar'
import HeroSection from '../components/HeroSection'


export default function Home() {
  return (
    <div className="debackground h-screen overflow-auto">
      <Head>
        <title>Dust Ecosystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="//db.onlinewebfonts.com/c/f05f148ec6596f0b75375fa566aaf1fe?family=Bely" rel="stylesheet" type="text/css"/>
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@DeGodsNFT" />
        <meta name="twitter:title" content="DeBuilders" />
        <meta name="twitter:description" content="From the DeGods who built cool sh*t" />
        <meta name="twitter:image" content="/dustecosystem.jpg" />
      </Head>
      <Navbar />
      <HeroSection />
    </div>
  )
}
