import Head from 'next/head'
import Navbar from '../components/Navbar'
import HeroSection from '../components/HeroSection'


export default function Home() {
  return (
    <div className="debackground h-screen overflow-auto">
      <Head>
        <title>Dust Ecosystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="//db.onlinewebfonts.com/c/f05f148ec6596f0b75375fa566aaf1fe?family=Bely" rel="stylesheet" type="text/css"/>
        <meta property="og:image" content="https://i.imgur.com/LVsJYp8.jpeg" />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="$DUST, a useless token that everyone on Solana uses" />
        <meta property="og:url" content="https://www.dustecosystem.xyz/" />
        <meta property="og:site_name" content="DustEcosystem" />
        <meta property="og:title" content="DustEcosystem" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@DeGodsNFT" />
        <meta name="twitter:title" content="DustEcosystem" />
        <meta name="twitter:description" content="$DUST, a useless token that everyone on Solana uses" />
        <meta name="twitter:image" content="https://i.imgur.com/LVsJYp8.jpeg" />
      </Head>
      <Navbar />
      <HeroSection />
    </div>
  )
}
